# Generated by Django 2.0 on 2017-12-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=300)),
                ('b_oname', models.CharField(max_length=100)),
                ('b_paddress1', models.CharField(max_length=100)),
                ('b_paddress2', models.CharField(max_length=100)),
                ('b_paddress3', models.CharField(max_length=100)),
                ('b_type', models.CharField(max_length=300)),
                ('b_sdate', models.CharField(max_length=10)),
                ('b_rnumber', models.CharField(max_length=100)),
                ('b_tnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GramaSevaDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_division', models.CharField(max_length=300)),
                ('gs_village', models.CharField(max_length=300)),
                ('gs_road', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=300)),
                ('o_purpose', models.CharField(max_length=100)),
                ('o_address1', models.CharField(max_length=100)),
                ('o_address2', models.CharField(max_length=100)),
                ('o_address3', models.CharField(max_length=100)),
                ('o_rnumber', models.CharField(max_length=100)),
                ('o_sdate', models.CharField(max_length=10)),
                ('o_nmembers', models.CharField(max_length=300)),
                ('o_sstaff', models.CharField(max_length=300)),
                ('o_pstaff', models.CharField(max_length=300)),
                ('o_asstaff', models.CharField(max_length=300)),
                ('o_apstaff', models.CharField(max_length=300)),
                ('o_tstaff', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_fname', models.CharField(max_length=100)),
                ('p_lname', models.CharField(max_length=300)),
                ('p_oname', models.CharField(max_length=300)),
                ('p_nic', models.CharField(max_length=12)),
                ('p_type', models.CharField(max_length=20)),
            ],
        ),
    ]
