# Generated by Django 2.0 on 2017-12-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_division',
            field=models.CharField(max_length=300, verbose_name='Grama Seva Division'),
        ),
    ]
