# Generated by Django 2.0 on 2017-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0005_auto_20171219_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(choices=[('MW', 'මහවත්ත'), ('SW', 'සේදවත්ත'), ('ER', 'අඇලකන්ද පාර'), ('SR', 'සුරැවල පාර'), ('RA', 'රදැල්ල'), ('TH', 'තල්ගස්මුල්ල')], default='MW', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_name',
            field=models.CharField(max_length=300, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_oname',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress1',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress2',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress3',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_rnumber',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_sdate',
            field=models.CharField(max_length=10, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_tnumber',
            field=models.CharField(max_length=10, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_type',
            field=models.CharField(max_length=300, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_name',
            field=models.CharField(max_length=300, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_fname',
            field=models.CharField(max_length=100, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_lname',
            field=models.CharField(max_length=300, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_nic',
            field=models.CharField(max_length=12, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_oname',
            field=models.CharField(max_length=300, verbose_name='පාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_type',
            field=models.CharField(max_length=20, verbose_name='පාර'),
        ),
    ]
