# Generated by Django 2.0 on 2017-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0006_auto_20171220_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='v_name',
            field=models.CharField(choices=[('MW', 'මහවත්ත'), ('SW', 'සේදවත්ත'), ('ER', 'අඇලකන්ද පාර'), ('SR', 'සුරැවල පාර'), ('RA', 'රදැල්ල'), ('TH', 'තල්ගස්මුල්ල')], default='MW', max_length=2, verbose_name='ගම'),
        ),
    ]
