# Generated by Django 2.0 on 2017-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0007_auto_20171220_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gramasevadivision',
            name='gs_road',
        ),
        migrations.RemoveField(
            model_name='gramasevadivision',
            name='gs_village',
        ),
        migrations.AddField(
            model_name='village',
            name='v_road',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='p_fname',
            field=models.CharField(max_length=100, verbose_name='මුල්  නම'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_lname',
            field=models.CharField(max_length=300, verbose_name='වාසගම'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_nic',
            field=models.CharField(max_length=12, verbose_name='ජාතික හැඳුනුම්පත් අංකය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_oname',
            field=models.CharField(max_length=300, verbose_name='අනිකුත් නම්'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_type',
            field=models.CharField(choices=[('GM', 'ගෘහමූලික'), ('WF', 'බිරිඳ'), ('DT', 'දුව'), ('SN', 'පුතා'), ('MO', 'මව'), ('FR', 'පියා'), ('EB', 'අයියා'), ('ES', 'අක්කා'), ('ST', 'නංගි'), ('BR', 'මල්ලි'), ('SB', 'සහෝදරයා'), ('SS', 'සහෝදරිය'), ('UN', 'මාමා'), ('AN', 'නැන්දා'), ('SM', 'මෙහෙකරු'), ('SF', 'මෙහකාරිය'), ('MN', 'මුනුබුරා'), ('MI', 'මිනිබිරිය')], default='GM', max_length=2, verbose_name='ඟාති සම්බන්ධය'),
        ),
    ]
