# Generated by Django 2.0 on 2017-12-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0008_auto_20171220_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='v_road',
            field=models.CharField(max_length=200, verbose_name='පාර'),
        ),
    ]
