# Generated by Django 2.0 on 2017-12-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0009_auto_20171220_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='b_name',
            field=models.CharField(max_length=300, verbose_name='ව්\u200dයාපාර නාමය'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_oname',
            field=models.CharField(max_length=100, verbose_name='අයිතිකරුගේ නම'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress1',
            field=models.CharField(max_length=100, verbose_name='අංකය'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress2',
            field=models.CharField(max_length=100, verbose_name='ලිපිනය 1'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_paddress3',
            field=models.CharField(max_length=100, verbose_name='ලිපිනය 2'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_rnumber',
            field=models.CharField(max_length=100, verbose_name='ලියාපදිංචි අංකය'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_sdate',
            field=models.CharField(max_length=10, verbose_name='ව්\u200dයාපාරය ආරම්භකල දිනය'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_tnumber',
            field=models.CharField(max_length=10, verbose_name='ව්\u200dයාපාරයේ දුරකථන අංකය'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='b_type',
            field=models.CharField(max_length=300, verbose_name='ව්\u200dයාපාර ස්වභාවය'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_address1',
            field=models.CharField(max_length=100, verbose_name='සංවිධානයේ ලිපිනය'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_address2',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_address3',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_apstaff',
            field=models.CharField(max_length=300, verbose_name='උප සභාපතිගේ  නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_asstaff',
            field=models.CharField(max_length=300, verbose_name='උපලේකම්ගේ නම  නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_name',
            field=models.CharField(max_length=300, verbose_name='සංවිධානයේ නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_nmembers',
            field=models.CharField(max_length=300, verbose_name='සමාජික සංඛ්\u200dයාව'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_pstaff',
            field=models.CharField(max_length=300, verbose_name='සභාපති ගේ  නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_purpose',
            field=models.CharField(max_length=100, verbose_name='සංවිධානය වීමේ අරමුණ'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_rnumber',
            field=models.CharField(max_length=100, verbose_name='සංවිධානයේ ලියාපදිංචි අංකය'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_sdate',
            field=models.CharField(max_length=10, verbose_name='සංවිධානය ආරම්භක දිනය'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_sstaff',
            field=models.CharField(max_length=300, verbose_name='ලේකම් ගේ නම  නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_tstaff',
            field=models.CharField(max_length=300, verbose_name='භාණ්ඩාගාරිකගේ නම'),
        ),
        migrations.AlterField(
            model_name='village',
            name='v_name',
            field=models.CharField(choices=[('MW', 'මහවත්ත'), ('SW', 'සේදවත්ත'), ('ER', 'ඇලකන්ද පාර'), ('SR', 'සුරුවල පාර'), ('RA', 'රදැල්ල'), ('TH', 'තල්ගස්මුල්ල')], default='MW', max_length=2, verbose_name='ගම'),
        ),
    ]
