# Generated by Django 2.0 on 2017-12-21 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0010_auto_20171220_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_shade', models.CharField(max_length=20)),
                ('h_floor', models.CharField(max_length=20)),
                ('h_wall', models.CharField(max_length=20)),
                ('h_water', models.CharField(max_length=20)),
                ('h_elec', models.CharField(max_length=20)),
                ('h_toilet', models.CharField(max_length=20)),
                ('h_lanTel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_period', models.CharField(max_length=10)),
                ('l_type', models.CharField(max_length=10)),
                ('l_lno', models.CharField(max_length=10)),
                ('l_kno', models.CharField(max_length=10)),
                ('l_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='p_birthdate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_donation',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_edu',
            field=models.CharField(default=1, max_length=10, verbose_name='අධ්\u200dයාපන සුදුසුකම්'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_job',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='රැකියාව'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_job_position',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='p_religion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
