# Generated by Django 2.0 on 2017-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0011_auto_20171221_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='h_elec',
            field=models.CharField(max_length=20, verbose_name='විදුලිය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_floor',
            field=models.CharField(max_length=20, verbose_name='ගෙබිම'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_lanTel',
            field=models.CharField(max_length=10, verbose_name='නිවසේ දුරකථන අංකය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_shade',
            field=models.CharField(max_length=20, verbose_name='වහලය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_toilet',
            field=models.CharField(max_length=20, verbose_name='වැසිකිලි'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_wall',
            field=models.CharField(max_length=20, verbose_name='බිත්ති'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_water',
            field=models.CharField(max_length=20, verbose_name='ජලය'),
        ),
        migrations.AlterField(
            model_name='land',
            name='l_kno',
            field=models.CharField(max_length=10, verbose_name='කට්ටි අංකය'),
        ),
        migrations.AlterField(
            model_name='land',
            name='l_lno',
            field=models.CharField(max_length=10, verbose_name='බලපත්\u200dර අංකය'),
        ),
        migrations.AlterField(
            model_name='land',
            name='l_period',
            field=models.CharField(max_length=10, verbose_name='පදිංචි කාලය'),
        ),
        migrations.AlterField(
            model_name='land',
            name='l_size',
            field=models.CharField(max_length=10, verbose_name='ඉඩමේ ප්\u200dරමාණය'),
        ),
        migrations.AlterField(
            model_name='land',
            name='l_type',
            field=models.CharField(choices=[('SI', 'සිංනක්කර'), ('AN', 'අනවසර'), ('WB', 'වාර්ෂික බලපත්\u200dර'), ('JB', 'ජයභූමි'), ('SB', 'ස්වර්ණභූමි'), ('KU', 'කුලීකරුවන්')], default='SI', max_length=10, verbose_name='ඉඩමේ වර්ගය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_birthdate',
            field=models.CharField(max_length=20, verbose_name='උපන්දිනය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_donation',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_gender',
            field=models.CharField(max_length=20, verbose_name='ස්ත්\u200dරී/ පුරුෂ භාවය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_job_position',
            field=models.CharField(max_length=20, verbose_name='තනතුර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_nationality',
            field=models.CharField(choices=[('SI', 'සිංහල'), ('TA', 'ද්\u200dරවිඩ'), ('MU', 'මුස්ලිම්'), ('BR', 'බර්ගර්'), ('MA', 'මැලේ'), ('OT', 'වෙනත්')], default='SI', max_length=20, verbose_name='ජාතිය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_religion',
            field=models.CharField(choices=[('BU', 'බෙද්ධ'), ('RC', 'කතෝලික'), ('HI', 'හින්දු'), ('IS', 'ඉස්ලාම්'), ('CH', 'ක්\u200dරිස්තියානි'), ('OT', 'වෙනත්')], default='BU', max_length=20, verbose_name='ඇාගම'),
        ),
    ]
