# Generated by Django 2.0 on 2017-12-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0012_auto_20171222_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='h_lanTel',
        ),
        migrations.AddField(
            model_name='house',
            name='h_lantel',
            field=models.BooleanField(default=False, verbose_name='නිවසේ දුරකථන අංකය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_elec',
            field=models.BooleanField(default=False, verbose_name='විදුලිය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_toilet',
            field=models.BooleanField(default=False, verbose_name='වැසිකිලි'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_water',
            field=models.BooleanField(default=False, verbose_name='ජලය'),
        ),
    ]
