# Generated by Django 2.0 on 2017-12-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0013_auto_20171222_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='h_floor',
            field=models.CharField(choices=[('CE', 'සිමෙන්ති'), ('TE', 'ටෙරාසෝ'), ('MB', 'මාබල්'), ('MT', 'මැටි'), ('CO', 'කොන්ක්\u200dරීට්')], default='CE', max_length=20, verbose_name='ගෙබිම'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_shade',
            field=models.CharField(choices=[('UL', 'උළු'), ('AS', 'ඇස්බැස්ටස්'), ('TH', 'තහඩු'), ('TS', 'තාරශීට්'), ('CO', 'කොන්ක්\u200dරීෟට්')], default='UL', max_length=20, verbose_name='වහලය'),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_wall',
            field=models.CharField(choices=[('BG', 'බලොාක් ගල්'), ('GD', 'ගඩොල්'), ('MT', 'මැටි'), ('LL', 'ලෑලි'), ('TH', 'තහඩු')], default='BG', max_length=20, verbose_name='බිත්ති'),
        ),
    ]
