# Generated by Django 2.0 on 2017-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0014_auto_20171222_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_birthdate',
            field=models.DateField(default='1/1/1977', verbose_name='උපන්දිනය'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_donation',
            field=models.CharField(choices=[('SD', 'සමෘද්ධි සහනාධාරය'), ('PD', 'මහජන ආධාර'), ('DD', 'රෝගාධාර'), ('SD', 'ශිෂ්\u200dයාධාර'), ('ED', 'වැඩිහිටි ආධාර')], default='SD', max_length=20, verbose_name='රජයෙන් ලබන ආධාර'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_edu',
            field=models.CharField(choices=[('PS', 'පාසල් යාමට පෙර'), ('PR', 'පෙර පාසැල්'), ('OF', '1-5 ශ්\u200dරේණිය දක්වා'), ('FO', '5 සිට සා/පෙළ දක්වා'), ('OP', 'සාමන්\u200dය පෙළ සමත්'), ('UA', 'උසස් පෙළ දක්වා'), ('AP', 'උසස් පෙළ සමත්'), ('DG', 'උපාධි හා ඊට ඉහල'), ('NS', 'කිසිදා පසැල් නොගිය')], default='OP', max_length=10, verbose_name='අධ්\u200dයාපන සුදුසුකම්'),
        ),
    ]
