# Generated by Django 2.0 on 2017-12-23 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0015_auto_20171223_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramasevadivision',
            name='gs_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gramasevadivision',
            name='gs_fname',
            field=models.CharField(default=1, max_length=100, verbose_name='මුල්  නම'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gramasevadivision',
            name='gs_lname',
            field=models.CharField(default=1, max_length=300, verbose_name='වාසගම'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gramasevadivision',
            name='gs_oname',
            field=models.CharField(default=1, max_length=300, verbose_name='අනිකුත් නම්'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gramasevadivision',
            name='gs_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_asstaff',
            field=models.CharField(max_length=300, verbose_name='උප ලේකම්ගේ නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_pstaff',
            field=models.CharField(max_length=300, verbose_name='සභාපතිගේ  නම'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='o_sstaff',
            field=models.CharField(max_length=300, verbose_name='ලේකම්ගේ නම'),
        ),
    ]
