# Generated by Django 2.0 on 2017-12-23 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0016_auto_20171223_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_end_date',
            field=models.DateTimeField(blank=True, verbose_name='සේවය අවසන් කල දිනය '),
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_fname',
            field=models.CharField(max_length=100, verbose_name='ග්\u200dරාමසේවක මහතාගේ මුල් නම'),
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_lname',
            field=models.CharField(max_length=300, verbose_name='ග්\u200dරාමසේවක මහතාගේ වාසගම'),
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_oname',
            field=models.CharField(max_length=300, verbose_name='ග්\u200dරාමසේවක මහතාගේ අනිකුත් නම්'),
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='සේවය පටන් ගත් දිනය'),
        ),
    ]
