# Generated by Django 2.0 on 2017-12-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_fname', models.CharField(max_length=100, verbose_name='මුල්  නම')),
                ('p_lname', models.CharField(max_length=300, verbose_name='වාසගම')),
                ('p_oname', models.CharField(max_length=300, verbose_name='අනිකුත් නම්')),
                ('p_nic', models.CharField(max_length=12, verbose_name='ජාතික හැඳුනුම්පත් අංකය')),
                ('p_type', models.CharField(choices=[('GM', 'ගෘහමූලික'), ('WF', 'බිරිඳ'), ('DT', 'දුව'), ('SN', 'පුතා'), ('MO', 'මව'), ('FR', 'පියා'), ('EB', 'අයියා'), ('ES', 'අක්කා'), ('ST', 'නංගි'), ('BR', 'මල්ලි'), ('SB', 'සහෝදරයා'), ('SS', 'සහෝදරිය'), ('UN', 'මාමා'), ('AN', 'නැන්දා'), ('SM', 'මෙහෙකරු'), ('SF', 'මෙහකාරිය'), ('MN', 'මුනුබුරා'), ('MI', 'මිනිබිරිය')], default='GM', max_length=2, verbose_name='ඟාති සම්බන්ධය')),
                ('p_edu', models.CharField(choices=[('PS', 'පාසල් යාමට පෙර'), ('PR', 'පෙර පාසැල්'), ('OF', '1-5 ශ්\u200dරේණිය දක්වා'), ('FO', '5 සිට සා/පෙළ දක්වා'), ('OP', 'සාමන්\u200dය පෙළ සමත්'), ('UA', 'උසස් පෙළ දක්වා'), ('AP', 'උසස් පෙළ සමත්'), ('DG', 'උපාධි හා ඊට ඉහල'), ('NS', 'කිසිදා පසැල් නොගිය')], default='OP', max_length=10, verbose_name='අධ්\u200dයාපන සුදුසුකම්')),
                ('p_job', models.CharField(max_length=10, verbose_name='රැකියාව')),
                ('p_job_position', models.CharField(max_length=20, verbose_name='තනතුර')),
                ('p_nationality', models.CharField(choices=[('SI', 'සිංහල'), ('TA', 'ද්\u200dරවිඩ'), ('MU', 'මුස්ලිම්'), ('BR', 'බර්ගර්'), ('MA', 'මැලේ'), ('OT', 'වෙනත්')], default='SI', max_length=20, verbose_name='ජාතිය')),
                ('p_religion', models.CharField(choices=[('BU', 'බෙද්ධ'), ('RC', 'කතෝලික'), ('HI', 'හින්දු'), ('IS', 'ඉස්ලාම්'), ('CH', 'ක්\u200dරිස්තියානි'), ('OT', 'වෙනත්')], default='BU', max_length=20, verbose_name='ඇාගම')),
                ('p_birthdate', models.DateField(default='1/1/1977', verbose_name='උපන්දිනය')),
                ('p_gender', models.CharField(max_length=20, verbose_name='ස්ත්\u200dරී/ පුරුෂ භාවය')),
                ('p_donation', models.CharField(choices=[('SD', 'සමෘද්ධි සහනාධාරය'), ('PD', 'මහජන ආධාර'), ('DD', 'රෝගාධාර'), ('SD', 'ශිෂ්\u200dයාධාර'), ('ED', 'වැඩිහිටි ආධාර')], default='SD', max_length=20, verbose_name='රජයෙන් ලබන ආධාර')),
            ],
        ),
    ]
