# Generated by Django 2.0 on 2017-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20171223_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_job',
            field=models.CharField(max_length=100, verbose_name='රැකියාව'),
        ),
    ]
