# Generated by Django 2.0 on 2017-12-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_p_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_pic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='ඡායාරූපය'),
        ),
    ]
