# Generated by Django 2.0 on 2017-12-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20171224_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_job',
            field=models.CharField(choices=[('GS', 'රාජ්\u200dය අංශය'), ('SG', 'අර්ධ රාජ්\u200dය අංශ්\u200dය'), ('PR', 'පේද්ගලික අංශය'), ('FJ', 'විදේශ රැකියා'), ('GS', 'රජයේ ආරක්ෂක අංශ'), ('SJ', 'ස්වයං රැකියා'), ('AG', 'කෘෂි කාර්මීක'), ('FH', 'ධීවර'), ('AS', 'සත්ව පාලන '), ('SS', 'සේවා යෝජක'), ('PN', 'විශ්ශ්\u200dරාමික'), ('HW', 'ගෘහණිය'), ('NJ', 'රැකියාවක් නොකරන'), ('SC', 'පාසැල් යන'), ('CH', 'ළදරු')], default='NJ', max_length=100, verbose_name='රැකියාව'),
        ),
    ]
