# Generated by Django 2.0.1 on 2018-01-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20171226_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
